### ISSUE TITLE
qinyi2018-CEPA 硬件开发

### ISSUE THREAD

**Issue by imwowzer** [imwowzer/Hardware-MSAN#1]
@qinyi2018 
### CEPA 硬件开发
- [X] 原理图设计（mindspeed DSP）
- [x] 提交PCB流程卡并跟踪PCB布板布线
    - [x] 预布局评估及问题汇总
    - [x] 确定防风条和防撞防护              ---已完成        
    - [x] 电路BOM整理并上传PLM
    - [x] 5套科研加工物料RDM发起申请
- [x] PCB投板
    - [x] PCB权限转交张红玉                ----已完成
    - [x] 结构VC权限转交 车双双          ---已完成
    - [x] 跟催樊艳丽将PCB数据上传PLM
    - [x] PCB科研加工RDM流程发起
    - [x] 杨俊反馈PCB回板时间    ---反馈时间为5月19号
- [x] 科研加工流程发起
    - [X] BOM整理
    - [X] 科研加工流程发起
    - [X] 跟踪加工进度
- [x] 机盘调试
    - [x] 电压测试点测电压值和阻抗
    - [x] 升级测试
    - [x] CPLD调试
    - [x] DFM测试
    - [x] Z接口测试
    - [x] EMC测试
    - [x] 热测试   
- [x] 白盒测试
    - [x] 电源测试
    - [x] 时钟测试
    - [x] 单盘测试
- [x] 中试问题解决
    - [x] 复位挂死问题
    - [ ] 远离矢量盘的槽位丢包问题

**Comment by qinyi2018** [comment]
@imwowzer 4月9号上午开评审会讨论防撞条和防风条如何处理

**Comment by imwowzer** [comment]
@qinyi2018 今天和小朱去荷田会所听培训

**Comment by qinyi2018** [comment]
@imwowzer test

**Comment by qinyi2018** [comment]
@imwowzer test2

**Comment by qinyi2018** [comment]
@imwowzer @test

**Comment by imwowzer** [comment]
@qinyi2018 test

**Comment by qinyi2018** [comment]
@imwowzer 

关于CEPA防风条、防撞条经过各位领导专家的讨论，形成以下结论：

1.防撞条：
防撞条去掉，
使用整版防护，毛坯需要修改，
责任人---叶书华/秦毅；

2.防风/防尘条：
保留左侧防风条（面板朝向人，左侧的防撞条），参照VCNA，
鉴于目前布局放不下的情况，主要考虑了横插的情况。
需要更新结构需求规格书和毛坯---责任人 叶书华/秦毅

3.LINE上的TVS去掉，修改原理图--责任人：秦毅
工艺最新规范要求，目前的布局方式TVS不满足要求，
且VD防护可以省掉TVS；

**Comment by qinyi2018** [comment]
@imwowzer @qiny2018 2018-04-10 CEPA详细设计评审 已发起

**Comment by qinyi2018** [comment]
@imwowzer @CEPA布局评审完成；
1. 整版防护，右上螺丝口孔位置；
  去掉背板测中间的螺丝孔，做折叠处理；    ---叶书华/余万春


2.C2507 Y 电容确认是否可以删除？   --秦毅/李慧芬

3.R22/R23 删除；  ---秦毅

4.感温芯片放中间，
需要根据01/06框子的实测结果，软件做两套调速标准。  --金曼丽，软件同事（到时候请王新柱总帮忙协调）；

5.以下是李振玉工的邮件评审：

邮件评审
1.近期制造部要求陶瓷电容/磁珠/晶振离板边或者VCUT至少8mm需求，这个还没明确加入可制造性要求。图示上板边阻容请调整至离板边3mm。另需加5mm工艺边。   ---余万春/李振玉


2.下长边如果所有贴装器件离板边有5mm，可以不加工艺边。  ---余万春/李振玉



3.相应的位号信息没有挪出本体内。  ---丝印信息，这个后期会一并处理，可以忽略


4.硬件立插电源模块，采用的ICPHG00535封装库，该库不能使用ICP0000633物料  ---秦毅

**Comment by qinyi2018** [comment]
@imwowzer CEPA PCB布线评审，会议纪要：
1. 线驱的丝印保留在pcb上，但是光辉文件（成品板子）去掉，放不下；
2.上班边阻容不够的地方工艺边做V-cut切掉；

3.S7层 AFE芯片的RX包地的孤铜请去掉；
4.S7层相邻的电源层，RX pin脚的地方电源挖掉，因为这部分是模拟的，且信号很弱，很容易导致DSL指标很差；
5.结构今天出毛坯，相关结构的备料数量是20套，请叶书华帮忙开始备料；

**Comment by imwowzer** [comment]
@qinyi2018 
今天完成PCB审核，争取今天投板，项目组要求5月5号PCB回板。

**Comment by imwowzer** [comment]
远离矢量盘的槽位丢包问题 单独开issue
