### ISSUE TITLE
liuhao798-GS8B 硬件开发

### ISSUE THREAD

**Issue by imwowzer** [imwowzer/Hardware-MSAN#2]
- [X] GS8B R1A 高低温
- [X] GS8B R1A EMC
- [x] GS8B R1A热测试
    - [x] 软件实现温度上报 
    - [x] 风扇智能调速验证
- [x] GS8B R1B 原理图
    - ~GS8B 电源条超高，原理图中需更换电源条~
        - ~Q:选60A的还是选6A的？~
        - ~A:目前的测试结果看，可以选6A的，还需要等软件功能完全实现后再看。~
- [X] GS8B R1B PCB流程卡提交并跟踪布局布线
    - [x] 梅细燕安排人员
        - 预计PCB投板时间：已投板，预计4月29日回板
    - [x] 王志远更新毛坯
- [X] GS8B 追加15套备料
    - [ ] 整理R1B版本BOM上传PLM
    - [X] 结构件紧急追加15套（结构件后期要做更改，面板有“**灯孔外露**”问题）
        - 预计结构件加工完成时间：**待与王志远确认**
- [x] GS8B R1B 15块PCB 投板
- [x] GS8B R1B CPLD修改
- [x] GS8B R1B 并行点灯验证
- [x] GS8B R1C 改版修复结构面板插电模块接触不良
- [x] GS8B R1C 兼容6A电源条设计

**Comment by imwowzer** [comment]
@pnzhu @liuhao798
### GS8B超高问题描述 
GS8B 上用的3V3转1V0电源条高度目前为12.7mm。刚才与结构沟通，就算让步到**13mm**（元件面到面板上内沿的理论高度），也要考虑焊接时有可能**因为焊料抬高0.5mm**。加上焊料高度后，电源条高度就达到**13.2mm**了。。。
***
### 改版方式
#### 无脑换60A贴装电源
- 支持3V3输入，1V0输出，大于8A电流，同时高度又＜12.5mm的只有60A的了
#### 评估下1V0实际电流大小
- 现在1V0电源条是按BCM56150手册里的最大值8A，使用场景24GE口+4个10G口来选的，然而实测GS8B的最大功耗不到20W，1V0电流也许并没有那么大，如果实测不超过5A，那么可以用优选表里6A的5pin插装电源条，这个高度只有10.2mm

**Comment by imwowzer** [comment]
@pnzhu @liuhao798 下午实测下1V0电流大小

**Comment by imwowzer** [comment]
@pnzhu @liuhao798 
刚才用示波器抓GS8B 1V0的最大电流，8个口两两自环情况下，最大不超过1.42A，可以按照EPMD ICP5设计来改
![gs8b_1v0](https://user-images.githubusercontent.com/31572378/38533957-1c3928c6-3cae-11e8-9e30-15bb48ddd2ab.png)

**Comment by imwowzer** [comment]
@pnzhu @liuhao798

晚上试了下将6A电源条飞线连到GS8B上，同时TRIM脚调压电阻也相应改为80K后，单盘不启动，测单盘上1V0测试点只有0.75V。
进一步测量电源条输出脚的电压还有0.93V，说明**飞线上有0.18V压降**，明天早上直接将电源条输出脚焊在盘子上再试试

**Comment by imwowzer** [comment]
@pnzhu

测试点的位号全部改成3V3，GND这样，按测试点电压来命名，会方便很多

**Comment by imwowzer** [comment]
@liuhao798 

GS8B R1A板 使用6A电源条的上电波形
![scope_0](https://user-images.githubusercontent.com/31572378/38597799-45a81d46-3d8c-11e8-8007-7de990e7c802.jpg)

**Comment by imwowzer** [comment]
@pnzhu 
请记录GS8B R1B版哪些电容被误删（位号和原理图截图），直接回复此邮件即可

**Comment by pnzhu** [comment]
缺20颗物料CC0S00453，位号如下：
C201,C202,C208,C209,C229,C272,C291-C293,C297-C299,C309,C315,C318,C331,C380-C382,C535

2018-04-28 


朱朴宁
烽火通信科技股份有限公司(Fiberhome Telecommunication Technologies Co.,LTD)
宽带业务产出线(Broadband and Service Application Business  Unit)
硬件开发部           
Mobile：+86-15927124670
Email: pnzhu@fiberhome.com
Address: 湖北省武汉市东湖新技术开发区高新四路6号
(No.6, Gaoxinsilu,East Lake High-tech Development zone，Wuhan, Hubei)
Postcode: 430205
http://www.fiberhome.com



发件人：Sun Wei <notifications@github.com>
发送时间：2018-04-25 10:34
主题：Re: [imwowzer/Hardware-MSAN] pnzhu&liuhao798-GS8B 硬件开发 (#2)
收件人："imwowzer/Hardware-MSAN"<Hardware-MSAN@noreply.github.com>
抄送："朱朴宁"<pnzhu@fiberhome.com>,"Mention"<mention@noreply.github.com>

@pnzhu
请记录GS8B R1B版哪些电容被误删（位号和原理图截图），直接回复此邮件即可
