### ISSUE TITLE
qinyi-CEPA-ipmux挂死解决方案

### ISSUE THREAD

**Issue by imwowzer** [imwowzer/Hardware-MSAN#22]

**Comment by qinyi2018** [comment]
小批量抽检50块单盘，去掉看门狗，然后查看挂死的概率是18/50；加上看门狗和软件规避，常温条件，目前观察这18块中有1块出现挂死，其他都OK

**Comment by qinyi2018** [comment]
> 
> 
> 小批量抽检50块单盘，去掉看门狗，然后查看挂死的概率是18/50；加上看门狗和软件规避，常温条件，目前观察这18块中有1块出现挂死，其他都OK

这块出问题的单盘目前常温（接串口）又挂24*4小时，暂未出现问题，还在挂。
