### ISSUE TITLE
AN5006-07/AN5006-09/AN5006-10/AN5121-4E/AN5161 电源指标确认

### ISSUE THREAD

**Issue by imwowzer** [imwowzer/Hardware-MSAN#4]
@liuhao798 郝愿愿要求填写的表格完成后，用回帖的方式上传附件

**Comment by liuhao798** [comment]
[副本MDU配置清单(1).xlsx](https://github.com/imwowzer/Hardware-MSAN/files/1888547/MDU.1.xlsx)
